sonar.projectKey=apds-v3-portal
sonar.projectName=APDS v3 - International Payments Portal
sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/build/**,**/keys/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
